version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: code-editor-backend
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    environment:
      - HOST_PROJECT_PATH=C:/Users/ramku/OneDrive/Desktop/new_folder/golang/golang_code_compiler_engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code-exec:/code-exec
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: code-editor-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8003
    container_name: compiler-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8003
    depends_on:
      - backend
